### PR TITLE
Alternative image request

### PR DESCRIPTION
**Pull request by owenjaques**
Implements: https://github.com/RcrossF/BCLiquorBot/issues/2

### CODE REVIEW

**Comment by owenjaques** [comment]
Testing right now. Before I implemented my code I made this search 
image
This gave me some results with notably COLONA - ROYAL WHITE not having an image 
image

**Comment by owenjaques** [comment]
I ran the same input with this new updated code and it gave me this! 
image
Pretty sure this is good to go!

**Review by michellejwatson — APPROVED** [review]
Looks good!

**Review by RcrossF — APPROVED** [review]
Some hot code 🔥

**Pull request merged**
